version: '3.3'

services:
  app:
    image: test-azuremonitor:1.0.0-SNAPSHOT
    ports:
      - 9090:9090
      - 9099:9099
    environment:
      APPLICATIONINSIGHTS_CONNECTION_STRING: InstrumentationKey=dc238825-fbab-4158-be48-c4ce2a35e9f5

  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9191:9090
    depends_on:
      - app