NUANCE: nuance

spring:
  application:
    name: test-azuremonitor

server:
  port: 9099

# Spring Boot management endpoint configuration
management:
  server:
    port: 9099
  info:
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
  health:
    probes:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Application-specific configuration
# TODO: You might want to change the name "sample-application"
sample-application:
  server-name: test-azuremonitor

---

spring:
  config:
    activate:
      on-profile: production
  main:
    banner-mode: "off"

# Graceful shutdown delay
# short value just for testing
estaGracefulShutdownWaitSeconds: 30
