{{- if eq .Values.networkPolicy.enabled true}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.standardLabels" (merge (dict "componentLabelValue" .Values.componentLabels.type) . ) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.standardSelectorLabels" (merge (dict "componentLabelValue" .Values.componentLabels.type) . ) | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: { }
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ambassador
          namespaceSelector: { }
    - from:
        - podSelector:
            matchLabels:
              app: prometheus
          namespaceSelector: { }
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/cluster-service: "true"
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

    - to:
        - podSelector:
            matchLabels:
              app: jaeger
          namespaceSelector:
            { }
    - to:
        - podSelector:
            matchLabels:
              app: istiod
          namespaceSelector:
            { }
{{- end }}