apiVersion: "v2"
name: "test-azuremonitor"
version: "1.0.0"
appVersion: "1.0.0"
description: "test-azuremonitor"
dependencies:
  - name: common
    repository: https://entrd-artifactory.nuance.com:443/artifactory/eiep-helm-dev
#    repository: file://iep-common-util
    version: 1.0.0